yt_dlp:
  source_address: "0.0.0.0"

ffmpeg:
  options: "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -vn"

bot:
  default_volume: 50
  leave_on_empty: true
  leave_delay: 300

niconico:
  email: ""
  password: ""

messages:
  join_voice_channel_first: ":warning: まずボイスチャンネルに参加してください。\n:warning: You need to be in a voice channel first."
  bot_not_in_voice_channel: ":warning: ボットがボイスチャンネルにいません。\n:warning: The bot is not in a voice channel."
  already_connected: ":information_source: 既にボイスチャンネルに接続しています。\n:information_source: Already connected to a voice channel."
  not_connected_to_your_channel: ":warning: あなたが参加しているボイスチャンネルに接続していません。\n:warning: Not connected to your voice channel."
  must_be_in_same_channel: ":warning: ボットと同じボイスチャンネルにいる必要があります。\n:warning: You must be in the same voice channel as the bot."

  now_playing: ":notes: 再生中: **{title}** (`{duration}`) - リクエスト: **{requester_display_name}**\n:notes: Now Playing: **{title}** (`{duration}`) - Requested by: **{requester_display_name}**"
  added_to_queue: ":ballot_box_with_check: キューに追加しました: **{title}** (`{duration}`) - リクエスト: **{requester_display_name}**\n:ballot_box_with_check: Added to queue: **{title}** (`{duration}`) - Requested by: **{requester_display_name}**"
  added_playlist_to_queue: ":ballot_box_with_check: プレイリストから **{count}** 曲をキューに追加しました。\n:ballot_box_with_check: Added **{count}** songs from the playlist to the queue."

  queue_empty: ":page_facing_up: キューは空です。\n:page_facing_up: The queue is empty."
  queue_ended: ":information_source: キューの再生が終了しました。\n:information_source: Playback queue has ended."
  # queue_title, queue_entry はEmbedで使われる想定なので、日英併記はEmbed生成側で行う
  # もしテキストで使うなら例:
  # queue_title: "現在のキュー ({count}曲) / Current Queue ({count} songs)"
  # queue_entry: "`{index}.` **{title}** (`{duration}`) - リク: <@{req_id}>\n`{index}.` **{title}** (`{duration}`) - Req: <@{req_id}>"

  skipped_song: ":track_next: スキップしました: **{title}**\n:track_next: Skipped: **{title}**"
  nothing_to_skip: ":information_source: スキップする曲がありません。\n:information_source: There is nothing to skip."
  stopped_playback: ":stop_button: 再生を停止し、キューをクリアしました。\n:stop_button: Playback stopped and queue cleared."
  playback_paused: ":pause_button: 再生を一時停止しました。\n:pause_button: Playback paused."
  playback_resumed: ":arrow_forward: 再生を再開しました。\n:arrow_forward: Playback resumed."

  volume_set: ":loud_sound: 音量を **{volume}%** に設定しました。\n:loud_sound: Volume set to **{volume}%**."
  invalid_volume: ":warning: 音量は0から200の間で指定してください。\n:warning: Volume must be between 0 and 200."
  queue_shuffled: ":twisted_rightwards_arrows: キューをシャッフルしました。\n:twisted_rightwards_arrows: Queue shuffled."
  now_playing_nothing: ":information_source: 現在再生中の曲はありません。\n:information_source: Nothing is currently playing."
  queue_cleared: ":wastebasket: キューをクリアしました。\n:wastebasket: Queue cleared."

  loop_off: ":arrow_right_hook: ループを解除しました。\n:arrow_right_hook: Loop turned off."
  loop_one: ":repeat_one: 現在の曲をループ再生します。\n:repeat_one: Looping current song."
  loop_all: ":repeat: キュー全体をループ再生します。\n:repeat: Looping entire queue."
  invalid_loop_option: ":warning: 無効なループオプションです。`off`, `one`, `all` のいずれかを指定してください。\n:warning: Invalid loop option. Please specify `off`, `one`, or `all`."

  song_removed: ":x: キューから削除しました: **{title}**\n:x: Removed from queue: **{title}**"
  invalid_queue_number: ":warning: 無効なキュー番号です。`{prefix}queue` で確認してください。\n:warning: Invalid queue number. Check with `{prefix}queue`."

  error_playing: ":x: 再生中にエラーが発生しました: `{error}`\n:x: An error occurred during playback: `{error}`"
  error_playing_stream: ":x: ストリームURLの取得または再生準備に失敗しました: `{error}`\n:x: Failed to get stream URL or prepare for playback: `{error}`"
  error_fetching_song: ":x: 曲情報の取得に失敗しました。URLや検索語を確認するか、別の曲をお試しください。エラー: `{error}`\n:x: Failed to fetch song information. Check the URL/search query or try another song. Error: `{error}`"

  leaving_voice_channel: ":wave: ボイスチャンネルから退出します。\n:wave: Leaving voice channel."
  auto_leave_empty_channel_countdown: ":timer: チャンネルに誰もいなくなったため、{timeout}秒後に自動退出します...\n:timer: Auto-leaving in {timeout} seconds as the channel is empty..."
  auto_leave_countdown_cancelled: ":white_check_mark: 自動退出カウントダウンをキャンセルしました。\n:white_check_mark: Auto-leave countdown cancelled."
  auto_left_empty_channel: ":door: 誰もいなくなったため、ボイスチャンネルから退出しました。\n:door: Left the voice channel because it became empty."

  search_no_results: ":mag: \"{query}\" の検索結果が見つかりませんでした。\n:mag: No results found for \"{query}\"."
  max_queue_size_reached: ":no_entry_sign: キューの最大サイズ ({max_size}曲) に達したため、これ以上追加できません。\n:no_entry_sign: Max queue size ({max_size} songs) reached. Cannot add more."