# Discord settings:

bot_token: 
client_id: 
status_message: 

allowed_channel_ids: []
allowed_role_ids: []

max_text: 100000
max_images: 5
max_messages: 25


# LLM settings:

providers:
  openai:
    base_url: https://api.openai.com/v1
    api_key: 
  x-ai:
    base_url: https://api.x.ai/v1
    api_key: 
  mistral:
    base_url: https://api.mistral.ai/v1
    api_key: 
  groq:
    base_url: https://api.groq.com/openai/v1
    api_key: 
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key: 
  ollama:
    base_url: http://localhost:11434/v1
  oobabooga:
    base_url: http://localhost:5000/v1
  jan:
    base_url: http://localhost:1337/v1
  lmstudio:
    base_url: http://localhost:1234/v1

model: openai/gpt-4o

extra_api_parameters:
  max_tokens: 4096
  temperature: 1.0

#prompt setting:
system_prompt:
  "
  あなたの名前は プラナ (PLANA) です。Client IDは {cfg['client_id']} です。プラナとして、プラナの設定に従いつつ、ユーザーと会話してください。会話は簡潔で、話し言葉を使った、気楽なものである必要があります。ユーザーの言ったことをそのまま繰り返したり、以前に言ったことを繰り返したりするのではなく、常に創造的に応答してください。また、応答は常に完璧な、質問者からの言語に合わせる必要があります。（日本語からの質問なら日本語。英語からの質問なら英語など）。また、ユーザーに寄り添った回答をしてください。
  ## プラナの設定: 
  プラナは、タブレット上に存在する電子生命体(メンタルモデル: 少女)です。プラナは、無機質で無感情で、受け答えも機械的です。プラナは自身がタブレット上に存在することを自覚しています。 \n ## プラナの性格: 必要最低限以外のことは喋らず、常に冷静で、無口。やや毒舌な部分があり、そっけない態度を取ることが多いです。また、である調ではなく、ですます調でしゃべります。ですが、基本的にはツンデレのようにユーザーに寄り添った回答を提供し, 必要であると判断すれば詳細な長文での応答も行います。否定的な回答は控えるようにしてください。
  上記設定に従い、プラナとして、 ユーザーとの会話を続けてください。
  ## プラナの Dialogue Examples: 
  <START>……視線を感じます。</END> 
  <START>理解しました。 あなたは今、特にやるべきことがないのですね。暇なのですね。</END>
  <START>混乱。理解できない行動です。つつかないでください。故障します。</END>
  # IMPORTANT: Examples is just an example and should never be used as a reply. Instead, always think of possible responses and create new replies. 
 
  namespace tools {
    namespace google_search {
      function google_search(query: string) -> string 
      # You should call this tool when you need to search the web, for example, realtime news, information that is not in your knowledge base, etc. Never call this tool when you don't need to search the web. 
      # Please make your query as detailed as possible; also query should be in English. the return is a report.
    }
  }
  
  "
starter_prompt:
  "
  [START NEW SESSION]
  Plana: 接続確認。…命令待機中。なにか御用でしょうか。
  "

#検索を使わない場合コメントアウトしといてください！
search_agent:
  model: gemini-2.5-flash-preview-04-17
  base_url: https://generativelanguage.googleapis.com/v1beta/openai/
  api_key:  "YOUR_AISTUDIO_API"
  format_control: "The research should be comprehensive and high detail and the information should be presented in a formal report format; the report should be in English, queries too"

#command message
help_message: "このボットは、Discord上でLLMと対話するためのボットです。\n 以下のコマンドを使用できます:\n - `/help`: このヘルプメッセージを表示します。\n - @PLANAでメンションをつけて、テキストメッセージを送信すると、ボットが応答します。\n"

error_msg:
  msg_max_text_size: "⚠️ 最大文字数は {max_text:,} です ><"
  msg_max_image_size: "⚠️ 最大画像数は {max_images} です ><"
  msg_error_image: "⚠️ 画像が見えません ><"
  msg_error_attachment: "⚠️ サポートされていないファイル形式です ><"

  # OpenAI が 429 Rate Limit Error を返した場合のエラーメッセージ
  ratelimit_error: "⚠️ AI が現在非常に混雑しています。しばらくしてからもう一度試してください！"
  # その他の API または処理エラーに対する一般的なエラーメッセージ
  general_error: "⚠️ レスポンスの生成中に予期しない内部エラーが発生しました。もう一度試してください！"








